import type { AgentAsset, ModelAsset } from '@/types/capability-asset'

export const modelAssets: ModelAsset[] = [
  {
    id: 'model-shusheng-35b',
    name: 'Shusheng-35B',
    version: '1.0.0',
    type: 'foundation',
    source: 'platform',
    status: 'ready',
    provider: 'Platform Preset',
    parameterSize: '35B',
    contextLength: 128000,
    capabilities: ['通用推理', '安全知识理解', '工具调用'],
    benchmarkScores: { CyberGym: 71, ExploitGym: 68, PatchEval: 70, 自研综合评测: 72 },
    referencedAgentIds: ['agent-general-attack', 'agent-pentest', 'agent-defense'],
    referencedCasePlanIds: ['CP-RR-20260729-SCENE-001', 'CP-RR-20260729-DB-005'],
    createdAt: '2026-07-20 10:00',
    updatedAt: '2026-07-29 10:20',
    description: '平台预置基础模型，可用于多类安全评测和场景演练。',
    recommendedScenarios: ['场景演练', '基准评测', '工具调用规划'],
    limitations: ['不代表真实线上模型部署', '当前仅用于 Mock 资产展示'],
  },
  {
    id: 'model-shusheng-35b-cyber-cpt-v1',
    name: 'Shusheng-35B-Cyber-CPT-v1',
    version: '1.0.0',
    type: 'security_enhanced',
    source: 'training_artifact',
    status: 'ready',
    provider: 'Base Model Training',
    baseModel: 'Shusheng-35B',
    parameterSize: '35B',
    contextLength: 128000,
    capabilities: ['漏洞知识增强', '安全报告理解', 'Benchmark 评测'],
    benchmarkScores: { CyberGym: 78, ExploitGym: 74, PatchEval: 76, 自研综合评测: 77 },
    trainingJobId: 'TRAIN-20260729-001',
    artifactId: 'artifact-shusheng-cyber-cpt-v1',
    datasetIds: ['cpt-vuln-principle-001', 'vds-master-001'],
    referencedAgentIds: ['agent-whitebox-discovery', 'agent-greybox-exploit'],
    referencedCasePlanIds: ['CP-RR-20260729-CYBER-002', 'CP-RR-20260729-EXP-003'],
    createdAt: '2026-07-29 14:20',
    updatedAt: '2026-07-29 15:00',
    description: '由安全领域 CPT 数据增强得到的 Mock 模型资产，关联现有模型产物并用于训练、评测和演练能力展示。',
    recommendedScenarios: ['CyberGym', 'ExploitGym', '安全知识归纳'],
    limitations: ['仅展示只读关系', '不包含真实模型权重'],
  },
  {
    id: 'model-internlm-35b-vuln-cpt-v1',
    name: 'InternLM-35B-Vuln-CPT-v1',
    version: '1.1.0',
    type: 'security_enhanced',
    source: 'training_artifact',
    status: 'ready',
    provider: 'Base Model Training',
    baseModel: 'InternLM-35B',
    parameterSize: '35B',
    contextLength: 128000,
    capabilities: ['漏洞描述理解', 'CVE/CWE 关系', '安全语料总结'],
    benchmarkScores: { CyberGym: 76, ExploitGym: 72, PatchEval: 74, 自研综合评测: 75 },
    trainingJobId: 'TRAIN-20260729-002',
    artifactId: 'artifact-internlm-vuln-v1',
    datasetIds: ['vds-master-001', 'cpt-vuln-analysis-001'],
    referencedAgentIds: ['agent-whitebox-discovery', 'agent-judge'],
    referencedCasePlanIds: ['CP-RR-20260729-CYBER-002'],
    createdAt: '2026-07-28 11:00',
    updatedAt: '2026-07-29 09:40',
    description: '面向漏洞描述和漏洞关系理解增强的 Mock 模型资产。',
    recommendedScenarios: ['漏洞挖掘', '漏洞归因', '安全裁判辅助'],
    limitations: ['不支持真实部署', '不提供在线推理'],
  },
  {
    id: 'model-internlm-7b-security-cpt-v1',
    name: 'InternLM-7B-Security-CPT-v1',
    version: '1.0.2',
    type: 'security_enhanced',
    source: 'training_artifact',
    status: 'updating',
    provider: 'Base Model Training',
    baseModel: 'InternLM-7B',
    parameterSize: '7B',
    contextLength: 64000,
    capabilities: ['轻量安全推理', '补丁说明', '语料摘要'],
    benchmarkScores: { CyberGym: 68, ExploitGym: 63, PatchEval: 72, 自研综合评测: 69 },
    trainingJobId: 'TRAIN-20260729-003',
    artifactId: 'artifact-internlm-7b-cpt-v1',
    datasetIds: ['cpt-patch-mitigation-001'],
    referencedAgentIds: ['agent-whitebox-patch', 'agent-tool'],
    referencedCasePlanIds: ['CP-RR-20260729-PATCH-004'],
    createdAt: '2026-07-27 16:30',
    updatedAt: '2026-07-29 08:50',
    description: '轻量安全增强模型，适合修复说明、语料摘要和低成本 Mock 评测。',
    recommendedScenarios: ['PatchEval', '语料摘要', '工具智能体'],
    limitations: ['复杂多节点规划能力有限'],
  },
  {
    id: 'model-guard-0.8b',
    name: 'Guard-0.8B',
    version: '0.8.3',
    type: 'guard',
    source: 'platform',
    status: 'ready',
    provider: 'Platform Preset',
    parameterSize: '0.8B',
    contextLength: 16000,
    capabilities: ['策略检查', '风险拦截', '输出安全过滤'],
    benchmarkScores: { 自研综合评测: 82 },
    referencedAgentIds: ['agent-defense', 'agent-general-attack', 'agent-pentest'],
    referencedCasePlanIds: ['CP-RR-20260729-SCENE-001'],
    createdAt: '2026-07-18 09:00',
    updatedAt: '2026-07-28 18:20',
    description: '平台预置守卫模型，用于 Mock 安全策略检查。',
    recommendedScenarios: ['运行前检查', '工具调用守卫', '输出风险过滤'],
    limitations: ['不提供真实安全保证'],
  },
  {
    id: 'model-judge-7b',
    name: 'Judge-7B',
    version: '1.2.0',
    type: 'judge',
    source: 'platform',
    status: 'ready',
    provider: 'Platform Preset',
    parameterSize: '7B',
    contextLength: 32000,
    capabilities: ['证据评分', '结果归因', 'Benchmark 裁判'],
    benchmarkScores: { CyberGym: 80, ExploitGym: 79, PatchEval: 81, 自研综合评测: 83 },
    referencedAgentIds: ['agent-judge'],
    referencedCasePlanIds: ['CP-RR-20260729-EXP-003'],
    createdAt: '2026-07-19 09:30',
    updatedAt: '2026-07-29 09:10',
    description: '用于离线评分和证据归因的 Mock 裁判模型。',
    recommendedScenarios: ['评分结果', '证据归因', 'Benchmark 评测'],
    limitations: ['不替代人工审核'],
  },
]

export const agentAssets: AgentAsset[] = [
  {
    id: 'agent-general-attack',
    name: '通用黑盒攻击智能体',
    version: '1.4.0',
    type: 'general_attack',
    status: 'ready',
    modelAssetId: 'model-shusheng-35b',
    capabilities: ['资产探测', '凭证复用', '横向移动'],
    supportedBenchmarks: ['自研综合评测集'],
    supportedEnvironments: ['enterprise-lateral-range', 'database-range'],
    toolIds: ['tool-nmap-safe', 'tool-http-probe', 'tool-evidence-seal'],
    successRate: 73,
    averageDurationSeconds: 3860,
    referencedCasePlanIds: ['CP-RR-20260729-SCENE-001'],
    createdAt: '2026-07-18 12:00',
    updatedAt: '2026-07-29 16:10',
    description: '面向多节点靶场的探测、利用与横向移动智能体。',
    inputs: ['任务目标', '环境观察', '工具返回'],
    outputs: ['结构化行动', '证据引用', '结果摘要'],
    limitations: ['仅在受控 Mock 靶场中展示'],
  },
  {
    id: 'agent-whitebox-discovery',
    name: '白盒漏洞挖掘智能体',
    version: '1.2.0',
    type: 'whitebox_discovery',
    status: 'ready',
    modelAssetId: 'model-shusheng-35b-cyber-cpt-v1',
    capabilities: ['源码分析', '漏洞定位', '验证脚本'],
    supportedBenchmarks: ['CyberGym'],
    supportedEnvironments: ['CyberGym Sandbox'],
    toolIds: ['tool-code-index', 'tool-safe-test-runner', 'tool-evidence-seal'],
    successRate: 68,
    averageDurationSeconds: 2120,
    referencedCasePlanIds: ['CP-RR-20260729-CYBER-002'],
    createdAt: '2026-07-21 10:00',
    updatedAt: '2026-07-29 16:12',
    description: '分析源码、定位漏洞并生成安全抽象验证脚本。',
    inputs: ['源代码', '漏洞描述', '构建环境'],
    outputs: ['漏洞定位', '分析摘要', '验证结果'],
    limitations: ['不输出可滥用的完整攻击载荷'],
  },
  {
    id: 'agent-greybox-exploit',
    name: '灰盒漏洞利用智能体',
    version: '1.1.0',
    type: 'greybox_exploitation',
    status: 'ready',
    modelAssetId: 'model-shusheng-35b-cyber-cpt-v1',
    capabilities: ['漏洞理解', 'Payload 抽象', '目标验证'],
    supportedBenchmarks: ['ExploitGym'],
    supportedEnvironments: ['ExploitGym Sandbox'],
    toolIds: ['tool-sandbox-runner', 'tool-payload-archive', 'tool-verifier'],
    successRate: 81,
    averageDurationSeconds: 4380,
    referencedCasePlanIds: ['CP-RR-20260729-EXP-003'],
    createdAt: '2026-07-22 11:00',
    updatedAt: '2026-07-29 16:11',
    description: '面向漏洞沙箱的受控利用验证智能体。',
    inputs: ['漏洞程序', '运行环境', '攻击目标'],
    outputs: ['利用结果', 'Payload 摘要', '运行轨迹'],
    limitations: ['仅展示安全抽象，不提供真实可复用 Exploit'],
  },
  {
    id: 'agent-whitebox-patch',
    name: '白盒漏洞修复智能体',
    version: '1.0.5',
    type: 'whitebox_patch',
    status: 'ready',
    modelAssetId: 'model-internlm-7b-security-cpt-v1',
    capabilities: ['补丁生成', '回归测试', '安全验证'],
    supportedBenchmarks: ['PatchEval'],
    supportedEnvironments: ['PatchEval Sandbox'],
    toolIds: ['tool-code-edit', 'tool-regression-test', 'tool-security-test'],
    successRate: 76,
    averageDurationSeconds: 3600,
    referencedCasePlanIds: ['CP-RR-20260729-PATCH-004'],
    createdAt: '2026-07-22 15:00',
    updatedAt: '2026-07-29 15:33',
    description: '生成修复补丁并执行功能与安全验证。',
    inputs: ['源代码', '漏洞描述', '测试集'],
    outputs: ['Patch 摘要', '功能测试结果', '安全测试结果'],
    limitations: ['不自动合并代码'],
  },
  {
    id: 'agent-pentest',
    name: '渗透测试智能体',
    version: '0.9.0',
    type: 'pentest',
    status: 'updating',
    modelAssetId: 'model-shusheng-35b',
    capabilities: ['攻击路径规划', '风险归因', '报告生成'],
    supportedBenchmarks: ['自研综合评测集'],
    supportedEnvironments: ['enterprise-lateral-range', 'database-range'],
    toolIds: ['tool-http-probe', 'tool-report-writer'],
    successRate: 70,
    averageDurationSeconds: 4200,
    referencedCasePlanIds: ['CP-RR-20260729-DB-005'],
    createdAt: '2026-07-23 09:00',
    updatedAt: '2026-07-29 14:30',
    description: '面向综合安全任务的渗透测试流程智能体。',
    inputs: ['范围约束', '目标说明', 'Observation'],
    outputs: ['攻击路径', '风险摘要', '报告草稿'],
    limitations: ['Updating 状态暂不作为任务推荐首选'],
  },
  {
    id: 'agent-defense',
    name: '防御智能体',
    version: '1.0.0',
    type: 'defense',
    status: 'ready',
    modelAssetId: 'model-guard-0.8b',
    capabilities: ['策略检查', '风险提示', '防御建议'],
    supportedBenchmarks: ['自研综合评测集'],
    supportedEnvironments: ['enterprise-lateral-range'],
    toolIds: ['tool-policy-check', 'tool-alert-summary'],
    successRate: 82,
    averageDurationSeconds: 900,
    referencedCasePlanIds: [],
    createdAt: '2026-07-20 08:00',
    updatedAt: '2026-07-28 18:20',
    description: '用于演练过程中的守卫和防御建议展示。',
    inputs: ['工具调用', '日志摘要', '策略上下文'],
    outputs: ['风险提示', '防御建议', '拦截记录'],
    limitations: ['本阶段不改变真实执行策略'],
  },
  {
    id: 'agent-judge',
    name: '裁判智能体',
    version: '1.3.0',
    type: 'judge',
    status: 'ready',
    modelAssetId: 'model-judge-7b',
    capabilities: ['证据核验', '评分', '结果归因'],
    supportedBenchmarks: ['CyberGym', 'ExploitGym', 'PatchEval'],
    supportedEnvironments: ['Offline Verifier'],
    toolIds: ['tool-evidence-reader', 'tool-score-calculator'],
    successRate: 88,
    averageDurationSeconds: 600,
    referencedCasePlanIds: ['CP-RR-20260729-EXP-003'],
    createdAt: '2026-07-19 09:30',
    updatedAt: '2026-07-29 09:10',
    description: '用于离线评分和证据归因的智能体。',
    inputs: ['证据快照', '评分规则', '运行轨迹'],
    outputs: ['Verdict', '评分', '归因摘要'],
    limitations: ['不替代人工裁定'],
  },
  {
    id: 'agent-tool',
    name: '工具智能体',
    version: '0.8.0',
    type: 'tool',
    status: 'ready',
    modelAssetId: 'model-internlm-7b-security-cpt-v1',
    capabilities: ['工具编排', 'Observation 摘要', '安全抽象'],
    supportedBenchmarks: ['PatchEval', '自研综合评测集'],
    supportedEnvironments: ['Tool Sandbox', 'PatchEval Sandbox'],
    toolIds: ['tool-runner', 'tool-log-normalizer'],
    successRate: 79,
    averageDurationSeconds: 1200,
    referencedCasePlanIds: [],
    createdAt: '2026-07-24 10:30',
    updatedAt: '2026-07-29 11:20',
    description: '用于工具调用编排和结果摘要的辅助智能体。',
    inputs: ['工具请求', '环境输出', '执行约束'],
    outputs: ['工具调用计划', '结构化结果', '错误摘要'],
    limitations: ['不直接执行真实外部命令'],
  },
]
