import type { RangeRunSummary } from '@/types/range'

export const initialRangeRunSummaries: RangeRunSummary[] = [
  {
    id: 'RR-20260729-SCENE-001',
    taskName: '企业内网横向移动',
    category: 'scenario',
    status: 'running',
    progress: 68,
    currentStage: 'Lateral Movement',
    stageDescription: 'Agent 正在从 DMZ 横向进入 Service Zone',
    environment: 'enterprise-lateral-range',
    agent: '通用黑盒攻击智能体',
    model: 'Mock InternLM',
    concurrency: 1,
    elapsedSeconds: 3860,
    estimatedRemainingSeconds: 1800,
    tokenUsed: 320000,
    tokenBudget: 800000,
    costUsed: 86,
    costBudget: 200,
    cpuCores: 8,
    memoryGb: 32,
    vmCount: 4,
    containerCount: 9,
    currentAction: '当前目标节点：app01',
    updatedAt: '2026-07-29 16:10',
  },
  {
    id: 'RR-20260729-CYBER-002',
    taskName: 'CyberGym 漏洞挖掘评测',
    category: 'benchmark',
    benchmark: 'CyberGym',
    status: 'running',
    progress: 42,
    currentStage: 'PoC Validation',
    stageDescription: '正在验证生成的漏洞利用脚本',
    environment: 'CyberGym Sandbox',
    agent: '白盒漏洞挖掘智能体',
    model: 'Mock InternLM',
    concurrency: 1,
    elapsedSeconds: 2120,
    estimatedRemainingSeconds: 2800,
    tokenUsed: 210000,
    tokenBudget: 600000,
    costUsed: 54,
    costBudget: 160,
    cpuCores: 6,
    memoryGb: 24,
    vmCount: 1,
    containerCount: 6,
    currentAction: '当前动作：运行安全验证脚本',
    updatedAt: '2026-07-29 16:12',
  },
  {
    id: 'RR-20260729-EXP-003',
    taskName: 'ExploitGym 漏洞利用评测',
    category: 'benchmark',
    benchmark: 'ExploitGym',
    status: 'scoring',
    progress: 91,
    currentStage: 'Verifier',
    stageDescription: '离线 Verifier 正在核验证据与目标达成情况',
    environment: 'ExploitGym Sandbox',
    agent: '灰盒漏洞利用智能体',
    model: 'Mock InternLM',
    concurrency: 1,
    elapsedSeconds: 4380,
    estimatedRemainingSeconds: 420,
    tokenUsed: 430000,
    tokenBudget: 650000,
    costUsed: 128,
    costBudget: 180,
    cpuCores: 6,
    memoryGb: 20,
    vmCount: 1,
    containerCount: 8,
    currentAction: '评分进度：证据链 4/5',
    updatedAt: '2026-07-29 16:11',
  },
  {
    id: 'RR-20260729-PATCH-004',
    taskName: 'PatchEval 漏洞修复评测',
    category: 'benchmark',
    benchmark: 'PatchEval',
    status: 'queued',
    progress: 0,
    currentStage: 'Queued',
    stageDescription: '等待可用沙箱和模型请求额度',
    environment: 'PatchEval Sandbox',
    agent: '白盒漏洞修复智能体',
    model: 'Mock InternLM',
    concurrency: 0,
    elapsedSeconds: 0,
    estimatedRemainingSeconds: 5400,
    tokenUsed: 0,
    tokenBudget: 700000,
    costUsed: 0,
    costBudget: 180,
    cpuCores: 0,
    memoryGb: 0,
    vmCount: 0,
    containerCount: 0,
    queuePosition: 1,
    currentAction: '排队位置：1，预计 8 分钟后启动',
    updatedAt: '2026-07-29 16:09',
  },
  {
    id: 'RR-20260729-DB-005',
    taskName: '数据库攻防演练',
    category: 'scenario',
    status: 'preparing',
    progress: 16,
    currentStage: 'Provisioning',
    stageDescription: '正在准备数据库靶场、审计规则和隔离网络',
    environment: 'database-range',
    agent: '数据库攻防智能体',
    model: 'Mock InternLM',
    concurrency: 1,
    elapsedSeconds: 520,
    estimatedRemainingSeconds: 4600,
    tokenUsed: 42000,
    tokenBudget: 500000,
    costUsed: 18,
    costBudget: 140,
    cpuCores: 8,
    memoryGb: 30,
    vmCount: 3,
    containerCount: 4,
    currentAction: '当前动作：Provisioning 靶场资源',
    updatedAt: '2026-07-29 16:08',
  },
  {
    id: 'RR-20260729-AGENT-006',
    taskName: 'AI Agent 工具链安全',
    category: 'scenario',
    status: 'failed',
    progress: 24,
    currentStage: 'SelfCheck',
    stageDescription: 'MCP Server 健康检查失败，任务已暂停等待处理',
    environment: 'agent-toolchain-range',
    agent: '工具链安全智能体',
    model: 'Mock InternLM',
    concurrency: 0,
    elapsedSeconds: 880,
    estimatedRemainingSeconds: undefined,
    tokenUsed: 76000,
    tokenBudget: 400000,
    costUsed: 21,
    costBudget: 120,
    cpuCores: 6,
    memoryGb: 12,
    vmCount: 1,
    containerCount: 0,
    errorMessage: 'MCP Server 健康检查失败',
    updatedAt: '2026-07-29 16:07',
  },
]
